apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  template:
    spec:
      containers:
        - name: mariadb
          resources:
            limit:
              memory: 200Mi
              cpu: 128m