apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
  labels:
    app: stateful-mariadb
    app.kubernetes.io/component: stateful-mariadb
    app.kubernetes.io/instance: stateful-mariadb
  name: stateful-mariadb
spec:
  replicas: 0
  selector:
    matchLabels:
      statefulset: stateful-mariadb
  template:
    metadata:
      labels:
        statefulset: stateful-mariadb
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/tomohide-sawada-dev/stateful-mariadb:latest
        name: stateful-mariadb
        env:
        - name: MARIADB_ROOT_PASSWORD
          value: passw0rd 
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mariadb-data
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  volumeClaimTemplates:
    - metadata:
        name: mariadb-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: gp3
        resources: 
          requests:
            storage: 1Gi
